name: xrange
version: 0.0.7
authors:
  - Ilia Gyrdymov <ilgyrd@gmail.com>
  - Sean Eagan <seaneagan1@gmail.com>
description: Provides classes and methods allowing to work with ranges
homepage: https://github.com/gyrdym/xrange

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.2
  grinder: ^0.8.3
  ml_tech: ^0.0.8
  test: ^1.2.0
